---
title: 使用tidymodels预测二分类变量
author: liyue
date: '2021-08-08'
slug: []
categories:
  - R
tags:
  - tidymodels
lastmod: '2021-08-08T21:06:31+08:00'
keywords: []
description: ''
comment: no
toc: yes
autoCollapseToc: no
postMetaInFooter: no
hiddenFromHomePage: no
contentCopyright: no
reward: no
mathjax: no
mathjaxEnableSingleDollar: no
mathjaxEnableAutoNumber: no
hideHeaderAndFooter: no
flowchartDiagrams:
  enable: no
  options: ''
sequenceDiagrams:
  enable: no
  options: ''
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,collapse = TRUE,warning = FALSE)
```

## 数据探索

children是结果变量，是一个2分类变量。

```{r}
library(tidyverse)

hotels <- readr::read_csv("E:/git/machine-learning-r-package/datasets/tidytuesday/data/2020/2020-02-11/hotels.csv")


hotel_stays <- hotels %>%
  filter(is_canceled == 0) %>%
  mutate(
    children = case_when( # 学习下case_when函数
      children + babies > 0 ~ "children",
      TRUE ~ "none"
    ),
    required_car_parking_spaces = case_when(
      required_car_parking_spaces > 0 ~ "parking",
      TRUE ~ "none"
    )
  ) %>%
  select(-is_canceled, -reservation_status, -babies)

hotel_stays
```

```{r}
hotel_stays %>% count(children) # children是结果变量
```

```{r}
skimr::skim(hotel_stays)
```

```{r}
# 写出这么刘畅的代码取决于对数据的理解以及对tidyverse包的理解
hotel_stays %>%
  mutate(arrival_date_month = factor(arrival_date_month, levels = month.name)) %>%
  count(hotel, arrival_date_month, children) %>%
  group_by(hotel, children) %>%
  mutate(proportion = n / sum(n)) %>%
  ggplot(aes(arrival_date_month, proportion, fill = children)) +
  geom_col(position = "dodge") +
  scale_y_continuous(labels = scales::percent_format()) + # 学习下百分比的用法
  facet_wrap(~hotel, nrow = 2) +
  labs(x = NULL, y = "Proportion of hotel stays", fill = NULL)
```

```{r}
hotel_stays %>%
  count(hotel, required_car_parking_spaces, children) %>%
  group_by(hotel, children) %>%
  mutate(proportion = n / sum(n)) %>%
  ggplot(aes(required_car_parking_spaces, proportion, fill = children)) +
  geom_col(position = "dodge") +
  scale_y_continuous(labels = scales::percent_format()) +
  facet_wrap(~hotel, nrow = 2) +
  labs(x = NULL, y = "Proportion of hotel stays", fill = NULL)
```

```{r}
library(GGally)

hotel_stays %>%
  select(
    children, adr,
    required_car_parking_spaces,
    total_of_special_requests
  ) %>%
  ggpairs(mapping = aes(color = children))
```

## 建模

### 数据准备

```{r}
hotels_df <- hotel_stays %>%
  select(
    children, hotel, arrival_date_month, meal, adr, adults,
    required_car_parking_spaces, total_of_special_requests,
    stays_in_week_nights, stays_in_weekend_nights
  ) %>%
  mutate_if(is.character, factor)

hotels_df <- hotels_df[1:1000,]
```


```{r}
library(tidymodels)
tidymodels_prefer()

set.seed(12)
hotel_split <- hotels_df %>% 
  initial_split()

hotel_train <- training(hotel_split)
hotel_test <- testing(hotel_split)

hotel_rec <- recipe(children ~ ., data = hotel_train) %>%
  themis::step_downsample(children) %>%
  step_dummy(all_nominal(), -all_outcomes()) %>%
  step_zv(all_numeric()) %>%
  step_normalize(all_numeric()) %>%
  prep()

hotel_rec
```

```{r}
# 提取准备好的训练集和测试集
train_proc <- bake(hotel_rec, new_data = NULL)
test_proc <- bake(hotel_rec, new_data = hotel_test)
```

### knn

```{r}
knn_spec <- nearest_neighbor(mode = "classification") %>% set_engine("kknn")
knn_fit <- knn_spec %>% fit(children ~ ., data = train_proc)

knn_fit
```

### 随机森林

```{r}
rf_spec <- rand_forest(mode = "classification") %>% set_engine("ranger")
rf_fit <- rf_spec %>% fit(children ~ ., data = train_proc)

rf_fit
```

### 决策树

```{r}
tree_spec <- decision_tree(mode = "classification") %>% set_engine("rpart")
tree_fit <- tree_spec %>% fit(children ~ ., data = train_proc)

tree_fit
```

## 评价模型

```{r}
set.seed(1234)

# 模特卡洛法交叉验证
validation_split <- mc_cv(data = train_proc, prop = 0.9, strata = children)
validation_split

validation_split$splits[[1]] %>% analysis() %>% dim()
validation_split$splits[[1]] %>% assessment()
```

```{r}
knn_res <- fit_resamples(
  knn_spec,
  children ~ ., 
  validation_split,
  control = control_resamples(save_pred = T)
)

knn_res
```

```{r}
knn_res %>% collect_metrics()
knn_res %>% collect_metrics(summarise=FALSE)
```

```{r}
knn_res %>% collect_predictions()
```


```{r}
rf_res <- fit_resamples(
  rf_spec,
  children ~ ., 
  validation_split,
  control = control_resamples(save_pred = T)
)

rf_res %>% collect_metrics()
```

```{r}
tree_res <- fit_resamples(
  tree_spec,
  children ~ ., 
  validation_split,
  control = control_resamples(save_pred = T)
)

tree_res %>% collect_metrics()
```


```{r}
knn_res %>%
  unnest(.predictions) %>%
  mutate(model = "kknn") %>%
  bind_rows(tree_res %>%
    unnest(.predictions) %>%
    mutate(model = "rpart")) %>%
  bind_rows(rf_res %>% 
    unnest(.predictions) %>% 
    mutate(model = "ranger")) %>% 
  group_by(model) %>%
  roc_curve(children, .pred_children) %>%
  ggplot(aes(x = 1 - specificity, y = sensitivity, color = model)) +
  geom_line(size = 1.5) +
  geom_abline(
    lty = 2, alpha = 0.5,
    color = "gray50",
    size = 1.2
  )
```

随机森林最好

```{r}
knn_conf <- knn_res %>% unnest(.predictions) %>% 
  conf_mat(children, .pred_class)

knn_conf
```

```{r}
knn_conf %>% autoplot()
```

```{r}
rf_fit %>% predict(new_data = test_proc, type = "prob") %>% 
  mutate(truth = hotel_test$children) %>% 
  roc_auc(truth, .pred_children)
```

